import type { Locale } from "./i18n";

export const bookingUrl = "https://calendar.app.google/HrpfJcFVepgRzhar6";

const fr = {
  nav: {
    projects: "Projets",
    education: "Interventions en école",
    automation: "Agents & automatisations IA",
    about: "À propos",
    book: "Prendre rendez-vous",
    menu: "Menu",
    close: "Fermer",
    language: "Langue",
  },
  home: {
    eyebrow: "Développeur senior · Intervenant · Concepteur d’automatisations",
    title: ["Je conçois,", "je transmets,", "j’automatise."],
    lead: "J’aide les équipes à construire des produits fiables, les écoles à former des développeurs opérationnels et les PME à transformer leurs tâches répétitives en systèmes utiles.",
    signature: "Dylan CDO",
    place: "Normandie",
    facets: ["Concevoir des produits", "Transmettre le métier", "Automatiser le travail"],
    primary: "Explorer les automatisations",
    secondary: "Voir mes projets",
    boardLabel: "Tableau d’opérations",
    boardStatus: "Système actif",
    pathsLabel: "Deux façons de travailler ensemble",
    pathsTitle: "Du savoir transmis au travail automatisé.",
    educationTitle: "Former des développeurs qui savent livrer.",
    educationText: "Modules, workshops, jurys et projets fil rouge pour les cursus Bac+2 à Bac+5, partout en France.",
    automationTitle: "Retirer les frictions du quotidien.",
    automationText: "Des agents et workflows IA reliés à vos outils, documentés et gardés sous contrôle humain.",
    selectedLabel: "Travaux choisis",
    selectedTitle: "Des preuves de conception et d’exécution.",
    closing: "Vous avez un cours à construire, un workflow à simplifier ou un produit à renforcer ?",
  },
  education: {
    eyebrow: "Interventions en école · France",
    title: "Faire comprendre. Faire pratiquer. Faire livrer.",
    lead: "J’interviens auprès d’étudiants de Bac+2 à Bac+5 avec une pédagogie ancrée dans le réel : contraintes métier, qualité du code, collaboration et mise en production.",
    cta: "Échanger pendant 30 minutes",
    email: "Écrire pour une intervention",
    topicsLabel: "Terrains d’intervention",
    topicsTitle: "Du code au système complet.",
    topics: [
      ["Frontend", "Angular, React, architecture d’interface et accessibilité."],
      ["Backend", "Node.js, NestJS, APIs, bases de données et logique métier."],
      ["Industrialisation", "Docker, CI/CD, qualité logicielle et observabilité."],
      ["Nouveaux usages", "Mobile et IA appliquée, avec un regard critique sur les outils."],
    ],
    methodLabel: "Méthode pédagogique",
    methodTitle: "Une progression visible, du brief à la livraison.",
    methodText: "Chaque séquence part d’un problème concret. Les étudiants formulent leurs choix, construisent, testent, documentent puis présentent ce qu’ils ont livré.",
    formatsLabel: "Formats possibles",
    formats: ["Modules récurrents", "Workshops", "Jurys", "Semaines intensives", "Projet fil rouge"],
    proofLabel: "Preuves pédagogiques",
    proof: [
      "Cadrage d’un projet fil rouge et jalons de progression.",
      "Supports, exercices et critères d’évaluation actionnables.",
      "Retours individualisés et soutenances orientées métier.",
    ],
    availability: "À distance partout en France. Présentiel selon calendrier.",
    faq: [
      { question: "Pour quels publics ?", answer: "Étudiants de Bac+2 à Bac+5 en développement. Les établissements ne sont pas cités." },
      { question: "Quels formats sont possibles ?", answer: "Modules récurrents, workshops, jurys, semaines intensives et projets fil rouge. La durée se cale au programme, sans forfait inventé." },
      { question: "Où intervenez-vous ?", answer: "À distance partout en France, et en présentiel selon le calendrier." },
      { question: "Comment se passe le premier échange ?", answer: "Un rendez-vous de 30 minutes, ou un email avec l’objet « Intervention en école ». Le tarif reste sur devis." },
    ],
  },
  automation: {
    eyebrow: "Agents & automatisations IA · PME",
    title: "Des workflows qui avancent, même quand votre attention est ailleurs.",
    lead: "Je conçois des automatisations sur mesure pour les équipes commerciales, administratives et support, de l’audit au déploiement, sans boîte noire incontrôlable.",
    cta: "Parler d’un workflow",
    email: "Décrire mon besoin par email",
    processLabel: "De l’idée au système",
    processTitle: "Une automatisation cadrée comme un produit.",
    process: ["Audit", "Prototype", "Déploiement", "Documentation", "Formation", "Maintenance optionnelle"],
    safeguardsLabel: "Garde-fous",
    safeguards: [
      "Accès minimaux aux outils et données.",
      "Actions importantes tracées et explicables.",
      "Validation humaine sur les opérations sensibles.",
      "Hébergement choisi selon vos contraintes.",
    ],
    stack: "TypeScript · APIs · n8n · Make · agents IA",
    launch: "Offre en lancement. Les exemples présentés sont des scénarios fictifs, conçus pour montrer la méthode sans inventer de résultats client.",
    hermes: "Hermes Agent, développé par Nous Research, peut être retenu lorsque le cadrage justifie ce niveau d’autonomie. Ce n’est jamais un choix par défaut.",
    faq: [
      { question: "À qui s’adresse l’offre ?", answer: "Aux PME et à leurs équipes commerciales, administratives ou support." },
      { question: "Quels outils utilisez-vous ?", answer: "TypeScript, APIs, n8n, Make et agents IA. Hermes Agent, de Nous Research, n’est retenu qu’après cadrage." },
      { question: "Comment les actions sensibles sont-elles contrôlées ?", answer: "Accès minimaux, traces des actions importantes et validation humaine avant les opérations sensibles." },
      { question: "Avez-vous des résultats clients ?", answer: "Non. L’offre est en lancement. Les scènes du site sont des scénarios démonstratifs, et le prix reste sur devis." },
    ],
  },
  about: {
    eyebrow: "À propos",
    title: "Relier la technique, la transmission et les usages.",
    lead: "Je suis Dylan Couto de Oliveira, développeur full-stack TypeScript. Mon travail consiste à rendre les systèmes plus clairs, les équipes plus autonomes et la technologie réellement utile.",
    pillars: [
      ["Concevoir", "Applications web, APIs et produits robustes, de l’architecture à la mise en production."],
      ["Transmettre", "Interventions adaptées au niveau des étudiants, avec des livrables et critères explicites."],
      ["Automatiser", "Workflows IA pragmatiques, intégrés aux outils existants et supervisés par l’humain."],
    ],
    method: "Je pars du contexte, rends les décisions visibles, livre par incréments et documente ce qui doit durer.",
    journeyLabel: "Parcours",
    journeyTitle: "De la production à la transmission.",
    journey: [
      ["2024 —", "Ingénieur logiciel · Campbell Scientific", "Applications industrielles Angular et NestJS pour l’acquisition de données critiques, utilisées dans plus de 30 pays."],
      ["2023 — 2024", "Développeur front-end · Operis", "Interfaces Angular pour des SaaS de collectivités : urbanisme, foncier, scolaire. Plateformes jusqu’à 15 000 utilisateurs par jour."],
      ["2022 — 2023", "Missions full-stack", "Livraisons web en agile, revues et qualité, dont des interfaces Angular et Next.js."],
      ["2020 — 2022", "Concepteur développeur", "Symfony, Vue.js, Docker et CI/CD. Lead d’une équipe de deux développeurs."],
      ["2024 —", "Interventions en école", "Modules et projet fil rouge : Node, Angular, bases de données, Docker et qualité logicielle. Les établissements restent anonymes."],
      ["2022 —", "Produits livrés", "DuoShot, MakeItGueznet, PoseLock, Pas envoyé, Cast Loop et des sites clients."],
    ],
    methodItems: [
      "Partir du contexte réel avant de choisir un outil.",
      "Rendre les décisions, les critères et les jalons visibles.",
      "Livrer par incréments testés, puis documenter ce qui doit durer.",
      "Garder une validation humaine sur ce qui est sensible.",
    ],
  },
  contact: {
    eyebrow: "Contact",
    title: "Quel sujet voulez-vous faire avancer ?",
    lead: "Choisissez le contexte le plus proche de votre besoin. L’agenda est le même, la conversation ne le sera pas.",
    options: [
      ["Intervention en école", "Construire un module, un workshop, un jury ou un projet fil rouge.", "Intervention en école"],
      ["Automatisation IA", "Identifier et prototyper un workflow utile à votre équipe.", "Projet d’automatisation IA"],
      ["Développement", "Échanger sur une mission ou une opportunité full-stack TypeScript.", "Opportunité développement"],
    ],
    faq: [
      { question: "Le rendez-vous est-il le même pour les écoles et les entreprises ?", answer: "Oui, un échange de 30 minutes. Le sujet de l’email et le suivi distinguent le contexte." },
      { question: "Les prix sont-ils affichés ?", answer: "Non. Les deux offres et les missions de développement restent sur devis." },
      { question: "Comment écrire directement ?", answer: "À contact@dylan-cdo.fr, avec un objet qui précise le besoin." },
    ],
  },
  common: {
    view: "Découvrir",
    book: "Prendre rendez-vous",
    email: "contact@dylan-cdo.fr",
    location: "Normandie · France · À distance",
    axes: { web: "Produits web", systems: "Systèmes complexes", pedagogy: "Pédagogie" },
  },
};

const en: typeof fr = {
  nav: { projects: "Projects", education: "Teaching", automation: "AI agents & automation", about: "About", book: "Book a call", menu: "Menu", close: "Close", language: "Language" },
  home: {
    eyebrow: "Senior developer · Instructor · Automation designer",
    title: ["I design,", "I teach,", "I automate."],
    lead: "I help teams build reliable products, schools train job-ready developers and SMEs turn repetitive work into useful systems.",
    signature: "Dylan CDO", place: "Normandy",
    facets: ["Design products", "Teach the craft", "Automate the work"],
    primary: "Explore automations", secondary: "View my work", boardLabel: "Operations board", boardStatus: "System active",
    pathsLabel: "Two ways to work together", pathsTitle: "From shared knowledge to automated work.",
    educationTitle: "Train developers who know how to ship.", educationText: "Modules, workshops, juries and capstone projects for higher education programmes across France.",
    automationTitle: "Remove friction from everyday work.", automationText: "AI agents and workflows connected to your tools, documented and kept under human control.",
    selectedLabel: "Selected work", selectedTitle: "Evidence of design and execution.",
    closing: "Need to build a course, simplify a workflow or strengthen a product?",
  },
  education: {
    eyebrow: "Teaching · France", title: "Understand it. Practise it. Ship it.",
    lead: "I teach students from two to five years into higher education with a practical approach grounded in real constraints, code quality, collaboration and deployment.",
    cta: "Talk for 30 minutes", email: "Email about teaching", topicsLabel: "Teaching areas", topicsTitle: "From code to complete systems.",
    topics: [["Frontend", "Angular, React, interface architecture and accessibility."], ["Backend", "Node.js, NestJS, APIs, databases and business logic."], ["Delivery", "Docker, CI/CD, software quality and observability."], ["Emerging uses", "Mobile and applied AI, with a critical eye on tools."]],
    methodLabel: "Teaching method", methodTitle: "Visible progress, from brief to delivery.", methodText: "Each sequence starts with a concrete problem. Students explain their choices, build, test, document and present what they shipped.",
    formatsLabel: "Possible formats", formats: ["Recurring modules", "Workshops", "Juries", "Intensive weeks", "Capstone project"],
    proofLabel: "Teaching evidence", proof: ["Capstone framing and progress milestones.", "Actionable material, exercises and evaluation criteria.", "Individual feedback and work-oriented presentations."],
    availability: "Remote anywhere in France. On-site depending on schedule.",
    faq: [
      { question: "Who is this for?", answer: "Students two to five years into a software development degree. Schools are not named." },
      { question: "Which formats are possible?", answer: "Recurring modules, workshops, juries, intensive weeks and capstone projects. Length follows the programme. No invented package." },
      { question: "Where can you teach?", answer: "Remotely anywhere in France, and on-site depending on the calendar." },
      { question: "How does the first conversation work?", answer: "A 30-minute call, or an email with the subject “Teaching engagement”. Pricing stays on quote." },
    ],
  },
  automation: {
    eyebrow: "AI agents & automation · SMEs", title: "Workflows that move forward while your attention is elsewhere.",
    lead: "I design custom automations for sales, administrative and support teams, from audit to deployment, without an uncontrollable black box.",
    cta: "Discuss a workflow", email: "Describe my need by email",
    processLabel: "From idea to system", processTitle: "Automation framed like a product.", process: ["Audit", "Prototype", "Deployment", "Documentation", "Training", "Optional maintenance"],
    safeguardsLabel: "Safeguards", safeguards: ["Minimum access to tools and data.", "Important actions remain traceable and explainable.", "Human approval for sensitive operations.", "Hosting chosen for your constraints."],
    stack: "TypeScript · APIs · n8n · Make · AI agents", launch: "This offer is launching. Every example shown is fictional and demonstrates the method without inventing client results.",
    hermes: "Hermes Agent, developed by Nous Research, may be selected when discovery justifies this level of autonomy. It is never a default choice.",
    faq: [
      { question: "Who is this for?", answer: "SMEs and their sales, administrative or support teams." },
      { question: "Which tools do you use?", answer: "TypeScript, APIs, n8n, Make and AI agents. Hermes Agent, by Nous Research, is selected only after discovery." },
      { question: "How are sensitive actions controlled?", answer: "Minimum access, traces of important actions, and human approval before sensitive operations." },
      { question: "Do you publish client results?", answer: "No. The offer is launching. Every scene on the site is a demonstration scenario, and pricing stays on quote." },
    ],
  },
  about: {
    eyebrow: "About", title: "Connecting technology, teaching and real use.",
    lead: "I’m Dylan Couto de Oliveira, a full-stack TypeScript developer. My work is about making systems clearer, teams more autonomous and technology genuinely useful.",
    pillars: [["Design", "Web applications, APIs and robust products, from architecture to production."], ["Teach", "Sessions adapted to student levels, with explicit deliverables and criteria."], ["Automate", "Practical AI workflows integrated with existing tools and supervised by humans."]],
    method: "I start from context, make decisions visible, ship in increments and document what needs to last.",
    journeyLabel: "Journey",
    journeyTitle: "From production work to teaching.",
    journey: [
      ["2024 —", "Software engineer · Campbell Scientific", "Industrial Angular and NestJS applications for critical data acquisition, used in more than 30 countries."],
      ["2023 — 2024", "Front-end developer · Operis", "Angular interfaces for local-authority SaaS: planning, land and schools. Platforms up to 15,000 users a day."],
      ["2022 — 2023", "Full-stack engagements", "Agile web delivery, reviews and quality, including Angular and Next.js interfaces."],
      ["2020 — 2022", "Developer", "Symfony, Vue.js, Docker and CI/CD. Led a team of two developers."],
      ["2024 —", "Teaching engagements", "Modules and a capstone: Node, Angular, databases, Docker and software quality. Schools stay unnamed."],
      ["2022 —", "Shipped products", "DuoShot, MakeItGueznet, PoseLock, Pas envoyé, Cast Loop and client sites."],
    ],
    methodItems: [
      "Start from the real context before choosing a tool.",
      "Make decisions, criteria and milestones visible.",
      "Ship tested increments, then document what needs to last.",
      "Keep human approval on anything sensitive.",
    ],
  },
  contact: {
    eyebrow: "Contact", title: "What would you like to move forward?", lead: "Choose the context closest to your need. The calendar is the same, the conversation will not be.",
    options: [["Teaching", "Build a module, workshop, jury or capstone project.", "Teaching engagement"], ["AI automation", "Identify and prototype a useful workflow for your team.", "AI automation project"], ["Development", "Discuss a full-stack TypeScript role or engagement.", "Development opportunity"]],
    faq: [
      { question: "Is the calendar the same for schools and companies?", answer: "Yes, a 30-minute call. The email subject and the analytics context keep the conversations distinct." },
      { question: "Are prices listed?", answer: "No. Both offers and development work stay on quote." },
      { question: "How do I write directly?", answer: "Email contact@dylan-cdo.fr with a subject that names the need." },
    ],
  },
  common: { view: "Discover", book: "Book a call", email: "contact@dylan-cdo.fr", location: "Normandy · France · Remote", axes: { web: "Web products", systems: "Complex systems", pedagogy: "Teaching" } },
};

export type ServiceCopy = typeof fr;

export function getServiceCopy(locale: Locale): ServiceCopy {
  return locale === "en" ? en : fr;
}
